#!/bin/bash
#SBATCH --job-name=lab1
#SBATCH --time=0:10:00
#SBATCH --ntasks-per-node=8
#SBATCH --nodes=1
#SBATCH --partition=batch
#SBATCH --output=lab1.out

module load intel/mpi4

for SIZE in 200 400 800 1200 1600 2000; do
    echo "========================================"
    echo "Запуск для матрицы ${SIZE}x${SIZE}"
    echo "========================================"
    mpirun ./lab1 . $SIZE
    echo ""
done
